language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'
  - hhvm
  - nightly
install:
  - composer install
#after_success:
#  - sed -e "s#$(pwd)/##g" -i build/logs/clover.xml
#  - vendor/bin/test-reporter
addons:
    - code_climate