language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'
  - hhvm
  - nightly
install:
  - composer install
addons:
    code_climate:
        repo_token: $CODE_CLIMATE_TOKEN
after_success:
  - vendor/bin/test-reporter